### ISSUE TITLE
Runtime Dependency Error

### ISSUE THREAD

**Issue by boverhof** [CCSI-Toolset/turb_sci_gate#25]
# Description
Appears the Unity dependency injection framework is looking for the older version of SimSinter and fails.

# FIX
Update the version in the XML file.

# Detail
```
(base) C:\Users\Administrator>more Desktop\testjosh\ACM_sinter_log.txt
SinterCosnumerConsole : Running

Unhandled Exception: Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "Turbine.Consumer.Contract.Behaviors.IConsumerRun", name = "(none)".
Exception occurred while: Calling constructor Turbine.Consumer.AspenTech.AspenSinterConsumer().
Exception is: FileNotFoundException - Could not load file or assembly 'Sinter, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving Turbine.Consumer.AspenTech.AspenSinterConsumer,(none) (mapped from Turbine.Consumer.Contract.Behaviors.IConsumerRun, (none))
  Calling constructor Turbine.Consumer.AspenTech.AspenSinterConsumer()
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Sinter, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Turbine.Consumer.SimSinter.SinterConsumerRun..ctor()
   at Turbine.Consumer.AspenTech.AspenSinterConsumer..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 27
   at BuildUp_Turbine.Consumer.AspenTech.AspenSinterConsumer(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at Turbine.Consumer.AppUtility.GetConsumerRunContract() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer\AppUtility.cs:line 40
   at Turbine.Consumer.Console.SinterConsumerConsole.Run() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Console\SinterConsumerConsole.cs:line 109
   at Turbine.Console.AspenSinterConsumerConsole.Main(String[] args) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\AspenSinterConsumerConsole\AspenSinterConsumerConsole.cs:line 83
SinterCosnumerConsole : Running

Unhandled Exception: Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "Turbine.Consumer.Contract.Behaviors.IConsumerRun", name = "(none)".
Exception occurred while: Calling constructor Turbine.Consumer.AspenTech.AspenSinterConsumer().
Exception is: FileNotFoundException - Could not load file or assembly 'Sinter, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving Turbine.Consumer.AspenTech.AspenSinterConsumer,(none) (mapped from Turbine.Consumer.Contract.Behaviors.IConsumerRun, (none))
  Calling constructor Turbine.Consumer.AspenTech.AspenSinterConsumer()
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'Sinter, Version=1.6.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Turbine.Consumer.SimSinter.SinterConsumerRun..ctor()
   at Turbine.Consumer.AspenTech.AspenSinterConsumer..ctor() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 27
   at BuildUp_Turbine.Consumer.AspenTech.AspenSinterConsumer(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at Turbine.Consumer.AppUtility.GetConsumerRunContract() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer\AppUtility.cs:line 40
   at Turbine.Consumer.Console.SinterConsumerConsole.Run() in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Console\SinterConsumerConsole.cs:line 109
   at Turbine.Console.AspenSinterConsumerConsole.Main(String[] args) in c:\Users\Administrator\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\AspenSinterConsumerConsole\AspenSinterConsumerConsole.cs:line 83

(base) C:\Users\Administrator>
```

**Comment by boverhof** [comment]
# Unity Runtime
```
(ccsi-foqus) C:\Users\Administrator\Desktop\FOQUS>more "\Program Files (x86)\Turbine\Lite\Clients\AspenSinterConsumerConsole.exe.config"
<configuration>
  <configSections>
    <sectionGroup name="userSettings" type="System.Configuration.UserSettingsGroup, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089">
      <section name="Turbine.Console.Properties.Settings" type="System.Configuration.ClientSettingsSection, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" allowExeDefinition="MachineToLocalUser" requirePermission="false"/>
    </sectionGroup>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false"/>
    <section name="unity" type="Microsoft.Practices.Unity.Configuration.UnityConfigurationSection, Microsoft.Practices.Unity.Configuration"/>
  </configSections>

  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Sinter" publicKeyToken="28ab44ce8d2de9de"/>
        <codeBase version="1.6.0.0" href="FILE://C:\Program Files (x86)\CCSI\SimSinter\Sinter.dll"/>
        <!--<codeBase href="FILE:///Program Files (x86)\CCSI\SimSinter\Sinter.dll" version="1.3.0.0"/>-->
        <!--<codeBase href="FILE:///Program Files\CCSI\SimSinter\Sinter.dll" version="1.3.0.0"/>-->
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
```

**Comment by boverhof** [comment]
# Update App.config
```
joshuas-mbp:turb_sci_gate boverhof$ find . -name App.[cC]onfig | xargs grep -s SINTER_HREF
./Master/ExcelSinterConsumerWindowsService/App.Config:        <codeBase href="SINTER_HREF" version="1.5.0.0" />
./Master/AspenSinterConsumerWindowsService/App.Config:        <codeBase href="SINTER_HREF" version="1.5.0.0" />
./Master/GPromsSinterConsumerConsole/App.config:        <codeBase href="SINTER_HREF" version="1.5.0.0" />
./Master/AspenSinterConsumerConsole/App.Config:        <codeBase href="SINTER_HREF" version="1.6.0.0" />
./Master/ExcelSinterConsumerConsole/App.Config:        <codeBase href="SINTER_HREF" version="1.5.0.0" />
```

**Comment by boverhof** [comment]
# Strong Name Signature v1.6.0.0
``` 
C:\Program Files (x86)\CCSI\SimSinter>sn.exe -T Sinter.dll

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.17929
Copyright (c) Microsoft Corporation.  All rights reserved.

Public key token is 28ab44ce8d2de9de

C:\Program Files (x86)\CCSI\SimSinter>
```

**Comment by boverhof** [comment]
### Rolled back to SimSinter v2.0.0 and built SimSinterInstaller.msi
Getting same error because wasn't signed with private key.
#### Traceback AspenSinterConsumerConsole.exe
```
  Calling constructor Turbine.Consumer.AspenTech.AspenSinterConsumer()
 ---> System.IO.FileLoadException: Could not load file or assembly 'Sinter, Version=1.6.0.0, Culture=neutral, PublicKeyToken=28ab44ce8d2de9de' or one of its dependencies. The private assembly was located outside the appbase directory. (Exception from HRESULT: 0x80131041)
   at Turbine.Consumer.SimSinter.SinterConsumerRun..ctor()
   at Turbine.Consumer.AspenTech.AspenSinterConsumer..ctor() in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.AspenTech\AspenSinterConsumer.cs:line 27
   at BuildUp_Turbine.Consumer.AspenTech.AspenSinterConsumer(IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicMethodBuildPlan.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at Turbine.Consumer.AppUtility.GetConsumerRunContract() in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer\AppUtility.cs:line 40
   at Turbine.Consumer.Console.SinterConsumerConsole.Run() in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\Turbine.Consumer.Console\SinterConsumerConsole.cs:line 109
   at Turbine.Console.AspenSinterConsumerConsole.Main(String[] args) in c:\Users\boverhof\Documents\Visual Studio 2012\Projects\turb_sci_gate\Master\AspenSinterConsumerConsole\AspenSinterConsumerConsole.cs:line 83
```

**Comment by boverhof** [comment]
@ksbeattie this issue should be resolved.  The prerelease installers for TurbineLite and SImSinter should work with FOQUS 3.1.0.0 now.

**Comment by jmorgan29** [comment]
I am still having issues working with SimSinter 2.1.0 and Turbine 2.3.0. When attempting to open Aspen files in the new SimSinter, I get the error message:

![Sinter Error](https://user-images.githubusercontent.com/11306727/131524337-be5c72b4-34c0-4ddc-98f7-388cfd667043.png)

When uploading a model in Turbine and attempting to run in FOQUS, I get:
![FOQUS Error 1 8_30_2021](https://user-images.githubusercontent.com/11306727/131524452-70109fb3-0f0b-4310-9718-aeb46ae8f3b0.png)

**Comment by boverhof** [comment]
# New Test VM 
SinterConfigUI works.  
![Screen Shot 2021-09-07 at 12 57 20 PM](https://user-images.githubusercontent.com/738295/132403755-0d3c4ef8-ab24-478f-a53f-838dbcbe1cbd.png)


![Screen Shot 2021-09-07 at 12 55 57 PM](https://user-images.githubusercontent.com/738295/132403778-608a7916-d787-430d-a614-ad4d01c338da.png)


![Screen Shot 2021-09-07 at 12 56 46 PM](https://user-images.githubusercontent.com/738295/132403792-120a806a-0273-4a2e-b670-a9cf9888624a.png)

**Comment by boverhof** [comment]
# ConsoleSinter Works
```
C:\Users\Administrator\Desktop\foqus\examples\test_files\Optimization\Model_Files>more inputs.json
[{}]
C:\Users\Administrator\Desktop\foqus\examples\test_files\Optimization\Model_Files>"\Program Files (x86)\CCSI\SimSinter\ConsoleSinter.exe" BFB_sinter_config_v6.2.json inputs.json outputs.json
Starting run 0
FINISHED. PRESS ENTER KEY TO EXIT PROGRAM.

C:\Users\Administrator\Desktop\foqus\examples\test_files\Optimization\Model_Files>
```
